# Generated by Django 5.1.4 on 2025-06-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=35)),
                ("code", models.CharField(max_length=8, unique=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("computer_science", "Computer Science"),
                            ("math", "Maths"),
                            ("natural science", "Natural Science"),
                        ],
                        default="Computer Science",
                        max_length=20,
                    ),
                ),
                ("credits", models.IntegerField(max_length=2)),
                ("image", models.ImageField(blank=True, null=True, upload_to="test")),
                ("module_count", models.IntegerField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="profilepicture",
            name="user",
        ),
        migrations.RemoveField(
            model_name="review",
            name="product",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="test"),
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("instructor", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("capacity", models.PositiveIntegerField()),
                ("enrolled", models.PositiveIntegerField(default=0)),
                ("schedule", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="accounts.course",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ShippingInfo",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="ProfilePicture",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
