# Generated by Django 5.1.4 on 2025-06-01 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_course_remove_order_user_remove_orderitem_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("about", models.CharField(max_length=255)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("computer_science", "Computer Science"),
                            ("math", "Maths"),
                            ("natural science", "Natural Science"),
                        ],
                        default="Computer Science",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="course",
            name="module_count",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="module",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="accounts.instructor",
            ),
        ),
    ]
